# Cloudflare Pages configuration
# This file is used by Cloudflare Pages to build and deploy your site

# Build configuration
[build]
  command = "npm run build"
  publish = "dist"

# Environment variables for build
[build.environment]
  NODE_VERSION = "18"

# Routes and redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
